.TH HELLO 1
.SH NAME
estimatepi \- Estimate the value of pi
.SH SYNOPSIS
.B estimatepi
.SH DESCRIPTION
On every iteration, this program asigns random coordinates to a two-valued array and determines via the standard Euclidean distance formula if the point is within a circle inscribed in a square. The proportion for a circle of radius one half to a square of side length one is 1/4 of pi. The estimation is described via: 4 * (number_points_inside / iterations).
